name: Android Cross-Compile with UPX

on:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        abi: [arm64-v8a, armeabi-v7a, x86, x86_64]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Android NDK
      uses: android-actions/setup-android@v2

    - name: Install UPX
      run: sudo apt-get install -y upx-ucl

    - name: Build for ${{ matrix.abi }}
      run: |
        mkdir -p build-${{ matrix.abi }}
        cd build-${{ matrix.abi }}
        cmake \
          -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake \
          -DANDROID_ABI=${{ matrix.abi }} \
          -DANDROID_PLATFORM=android-21 \
          ..
        make -j$(nproc)

    - name: Compress with UPX
      run: |
        cd build-${{ matrix.abi }}
        upx --ultra-brute --best --lzma --all-methods --all-filters --force *.so
        echo "Compressed libraries for ${{ matrix.abi }}:"
        ls -la *.so

    - name: Upload compressed libraries
      uses: actions/upload-artifact@v4
      with:
        name: android-${{ matrix.abi }}-compressed
        path: build-${{ matrix.abi }}/*.so
